export const dark = {
    enabledOpacity: 1,
    disabledOpacity: 0.5,
    touchOpacity: 0.7,
    primary: '#4D8EFF',
    background: '#11121A',
    backgroundDivide: '#1B1C28',
    secondary: '#6D7278',
    overlayBackground: 'rgba(0,0,0,.5)',
    card: '#1B1C28',
    cardDivide: '#2C2E41',
    ipoCard: '#2C2D38',
    stockLabel: '#222841',
    snapCard: '#1B2036',
    primaryText: '#fff',
    secondaryText: '#A5A5A5',
    disabled: 'rgba(#fff, .2)',
    error: '#CD5252',
    success: '#0AA88B',
    warning: '#E18721',
    info: '#5A5B6A',
    helper: '#5A5B6A',
    transparent: 'transparent',
    signatureBackground: '#fff'
    // foreground: '#FFFFFF',
    // card: '#1b1c28',
    // text: '#FFFFFF',
    // textMuted: '#A5A5A5',
    // border: '#2C2D3C',
    // ring: '#4D8EFF',
    // tint: '#000',
};

export const light = {
    ...dark,
    background: '#fff',
}; // Placeholder for light theme, can be customized later