export const dark = {
    rounded: {
        background: '#1b1c28',
        borderRadius: 22,
        borderWidth: 1,
        borderBottomWidth: 1,
        borderColor: 'transparent',
        borderActive: '#4D8EFF',
        borderError: '#FF4D4F',
        placeholder: '#6D7278',
        color: '#fff',
        iconColor: '#ffffff5c',
        caretColor: '#4D8EFF',
    },
    underline: {
        background: 'transparent',
        borderRadius: 0,
        borderWidth: 0,
        borderBottomWidth: 1,
        borderColor: '#6D7278',
        borderActive: '#4D8EFF',
        borderError: '#FF4D4F',
        placeholder: '#6D7278',
        color: '#fff',
        iconColor: '#ffffff5c',
        caretColor: '#4D8EFF',
    },
    outline: {
        background: 'transparent',
        borderRadius: 8,
        borderWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#6D7278',
        borderActive: '#4D8EFF',
        borderError: '#FF4D4F',
        placeholder: '#6D7278',
        color: '#fff',
        iconColor: '#ffffff5c',
        caretColor: '#4D8EFF',
    },
}
export const light = {
    ...dark,
}; // Placeholder for light theme, can be customized later